### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by Xupack88** [TheLime1/aichat-cli#25]
When I run **python3 gpt_cli.py**, I get the following error message:

```
Traceback (most recent call last):
  File "/home/redacted/Git/gpt-cli/gpt_cli.py", line 10, in <module>
    from gptcli.bingfunc import *
  File "/home/redacted/Git/gpt-cli/gptcli/bingfunc.py", line 1, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
  File "/home/redacted/.local/lib/python3.10/site-packages/EdgeGPT.py", line 23, in <module>
    from src.helpers.chathub.chathub import ChatHub
ModuleNotFoundError: No module named 'src'
```

**Comment by TheLime1** [comment]
patched , make sure to `pip install -r requirements .txt` again
