### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'python'

### ISSUE THREAD

**Issue by Xupack88** [TheLime1/aichat-cli#27]
Hate to be a nuisance, but now I get the following error no matter which command I run:

```
Token file not found or empty. Generating token...
Traceback (most recent call last):
  File "/home/redacted/Git/aichat-cli/gpt_cli.py", line 114, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/redacted/Git/aichat-cli/gpt_cli.py", line 32, in main
    generate_poe_token(dir)
  File "/home/redacted/Git/aichat-cli/gptcli/poefunc.py", line 110, in generate_poe_token
    subprocess.run(["python", gen_file], check=True)
  File "/usr/lib64/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

**Comment by TheLime1** [comment]
its an issue with you python , no with the repo , cheeck if python in path

**Comment by Xupack88** [comment]
I'm running openSUSE Kalpa (MicroOs) and you were right in that it was an issue with python installation out of the box.

Here's how I fixed it in case someone in the future sees this:

Open up a terminal and enter these commands:
```
1. sudo transactional-update shell
2. ln -s /usr/bin/python3 /usr/bin/python
3. exit
4. sudo reboot or systemctl reboot
```
Optionally add this line to your .bashrc and don't forget to `source ~/.bashrc` or reboot for it to take effect:
`alias python='python3'`
