### ISSUE TITLE
GPT4 does not work - Invalid or missing token.

### ISSUE THREAD

**Issue by Tone866** [TheLime1/aichat-cli#4]
I created the token with `python token_gen.py`, but gpt_cli crashes if I choose GPT4.

```
│$ python gpt_cli.py


    __     _                        ______ __            __
   / /    (_)____ ___   ___        / ____// /_   ____ _ / /_
  / /    / // __ `__ \ / _ \      / /    / __ \ / __ `// __/
 / /___ / // / / / / //  __/     / /___ / / / // /_/ // /_
/_____//_//_/ /_/ /_/ \___/______\____//_/ /_/ \__,_/ \__/
                          /_____/

[1] - Sage (tweaked 3.5gpt_turbo) 4096 token
[2] - ChatGPT (default) 4096 token
[3] - GPT4(slower,more accurate) 8192 token
[4] - Claude (default, FAST) 4500 token
[5] - Claude+ (more creative, FASTER) 9000 token
[6] - Claude_100K (BETA, very long messages) 100000 token

Choose your bot: 3
Traceback (most recent call last):
  File "/home/user/gpt-cli/gpt_cli.py", line 270, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/gpt-cli/gpt_cli.py", line 236, in main
    response = premuim_chatbot(input_message, bot)
  File "/home/user/gpt-cli/gpt_cli.py", line 113, in premuim_chatbot
    raise e
  File "/home/user/gpt-cli/gpt_cli.py", line 104, in premuim_chatbot
    raise e
  File "/home/user/gpt-cli/gpt_cli.py", line 80, in premuim_chatbot
    client = poe.Client(current_premium_token)
  File "/home/user/.local/lib/python3.10/site-packages/poe.py", line 124, in __init__
    self.setup_connection()
  File "/home/user/.local/lib/python3.10/site-packages/poe.py", line 129, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "/home/user/.local/lib/python3.10/site-packages/poe.py", line 168, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
  File "/home/user/.local/lib/python3.10/site-packages/poe.py", line 49, in request_with_retries
    raise RuntimeError("Invalid or missing token.")
RuntimeError: Invalid or missing token.
```

**Comment by TheLime1** [comment]
do you have the last version of the code ?
 because in the last version the code will try other tokens :
 
![image](https://github.com/TheLime1/gpt-cli/assets/47940043/e581fca5-e6b5-4d3f-9cbd-9779fb6ce483)

**Comment by Tone866** [comment]
Yes, I cloned this git 3 hours ago.

**Comment by TheLime1** [comment]
patched
