### ISSUE TITLE
Chrome binary not found

### ISSUE THREAD

**Issue by adrianmihalko** [TheLime1/aichat-cli#5]
Hi,

For some reason I get this error:

```
@ubuntu:~/scripts/gpt-cli$ pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: poe-api==0.3.1 in /home/madrian/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied: selenium in /home/madrian/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (4.9.1)
Requirement already satisfied: pyperclip==1.8.2 in /home/madrian/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.8.2)
Requirement already satisfied: prompt_toolkit in /home/madrian/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (3.0.38)
Requirement already satisfied: python-socks in /home/madrian/.local/lib/python3.10/site-packages (from poe-api==0.3.1->-r requirements.txt (line 1)) (2.3.0)
Requirement already satisfied: requests[socks] in /home/madrian/.local/lib/python3.10/site-packages (from poe-api==0.3.1->-r requirements.txt (line 1)) (2.28.1)
Requirement already satisfied: websocket-client in /usr/lib/python3/dist-packages (from poe-api==0.3.1->-r requirements.txt (line 1)) (1.2.3)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /home/madrian/.local/lib/python3.10/site-packages (from selenium->-r requirements.txt (line 2)) (1.26.13)
Requirement already satisfied: trio~=0.17 in /home/madrian/.local/lib/python3.10/site-packages (from selenium->-r requirements.txt (line 2)) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in /home/madrian/.local/lib/python3.10/site-packages (from selenium->-r requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: certifi>=2021.10.8 in /home/madrian/.local/lib/python3.10/site-packages (from selenium->-r requirements.txt (line 2)) (2022.12.7)
Requirement already satisfied: wcwidth in /home/madrian/.local/lib/python3.10/site-packages (from prompt_toolkit->-r requirements.txt (line 4)) (0.2.6)
Requirement already satisfied: attrs>=19.2.0 in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (22.1.0)
Requirement already satisfied: sortedcontainers in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (1.10)
Requirement already satisfied: idna in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: outcome in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: sniffio in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /home/madrian/.local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: wsproto>=0.14 in /home/madrian/.local/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/madrian/.local/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium->-r requirements.txt (line 2)) (1.7.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/madrian/.local/lib/python3.10/site-packages (from requests[socks]->poe-api==0.3.1->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: h11<1,>=0.9.0 in /home/madrian/.local/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->-r requirements.txt (line 2)) (0.14.0)
madrian@ubuntu:~/scripts/gpt-cli$ python3 gpt_cli.py
Token file not found or empty. Generating token...
Enter your email: example@gmail.com
Traceback (most recent call last):
  File "/home/madrian/scripts/gpt-cli/token_gen.py", line 20, in <module>
    driver = webdriver.Chrome(options=options)
  File "/home/madrian/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/home/madrian/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/home/madrian/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/madrian/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/madrian/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/madrian/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x561921134133 <unknown>
#1 0x561920e68966 <unknown>
#2 0x561920e8fb57 <unknown>
#3 0x561920e8e07b <unknown>
#4 0x561920ecd9ad <unknown>
#5 0x561920ecd18f <unknown>
#6 0x561920ec49a3 <unknown>
#7 0x561920e9946a <unknown>
#8 0x561920e9a55e <unknown>
#9 0x5619210f3cae <unknown>
#10 0x5619210f78fe <unknown>
#11 0x561921100f20 <unknown>
#12 0x5619210f8923 <unknown>
#13 0x5619210cbc0e <unknown>
#14 0x56192111bb08 <unknown>
#15 0x56192111bc97 <unknown>
#16 0x56192112c113 <unknown>
#17 0x7fd4a6142b43 <unknown>

Traceback (most recent call last):
  File "/home/madrian/scripts/gpt-cli/gpt_cli.py", line 270, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/madrian/scripts/gpt-cli/gpt_cli.py", line 197, in main
    generate_token()
  File "/home/madrian/scripts/gpt-cli/gpt_cli.py", line 137, in generate_token
    subprocess.run(["python", "token_gen.py"], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'token_gen.py']' returned non-zero exit status 1.
```

**Comment by TheLime1** [comment]
Are running it on Linux machine?
See #3

**Comment by adrianmihalko** [comment]
Yep, on a headless server. Manually editing token.txt is working. It would be nice to get it work without need to install Chrome. Thanks for this tool.
