### ISSUE TITLE
KeyError: 'payload'

### ISSUE THREAD

**Issue by ScarletMaid66** [TheLime1/aichat-cli#61]
Anyway to fix that, or is that an issue on my side?

Traceback (most recent call last):
  File "C:\Users\AHA\Downloads\aichat-cli-main\aichat-cli-main\aichat\chatcli.py", line 114, in <module>
    asyncio.run(main())
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\AHA\Downloads\aichat-cli-main\aichat-cli-main\aichat\chatcli.py", line 108, in main
    response = chatbot(input_message, current_bot, dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AHA\Downloads\aichat-cli-main\aichat-cli-main\aichat\poefunc.py", line 13, in chatbot
    client = poe.Client(token)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 123, in __init__
    self.connect_ws()
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 366, in connect_ws
    self.setup_connection()
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AHA\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 198, in get_next_data
    self.viewer = next_data["props"]["pageProps"]["payload"]["viewer"]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^

**Comment by TheLime1** [comment]
if erorr still happen re-open
